#!/usr/bin/env python3
"""
Build IDF table for BM25 scoring from the embedding index.

Reads: src/assets/parser/embedding-index.json
Writes: src/engine/parser/bm25_data.lua

Output is a pure Lua module (no io, no external deps) compatible with Fengari.
"""

import json
import math
import re
import os

STOP_WORDS = {
    "the", "a", "an", "some", "to", "at", "on", "in", "of", "my", "its",
    "this", "that", "is", "it", "i", "and", "or", "with", "for", "up",
    "down", "around"
}

def tokenize(text):
    """Match the Lua tokenizer: lowercase, strip punctuation, remove stop words, dedupe."""
    text = text.lower()
    text = re.sub(r"[^a-z0-9\-]", " ", text)
    tokens = []
    seen = set()
    for word in text.split():
        if word not in STOP_WORDS and word not in seen:
            tokens.append(word)
            seen.add(word)
    return tokens

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(script_dir)
    index_path = os.path.join(repo_root, "src", "assets", "parser", "embedding-index.json")
    output_path = os.path.join(repo_root, "src", "engine", "parser", "bm25_data.lua")

    with open(index_path, "r", encoding="utf-8") as f:
        index = json.load(f)

    phrases = index["phrases"]
    N = len(phrases)

    # Tokenize all phrases
    doc_tokens = []
    total_length = 0
    doc_freq = {}  # token -> number of docs containing it

    for phrase in phrases:
        tokens = tokenize(phrase["text"])
        doc_tokens.append(tokens)
        total_length += len(tokens)
        seen = set(tokens)
        for t in seen:
            doc_freq[t] = doc_freq.get(t, 0) + 1

    avg_doc_length = total_length / N if N > 0 else 0

    # Compute IDF: ln((N - n + 0.5) / (n + 0.5) + 1)
    idf = {}
    for token, n in doc_freq.items():
        idf[token] = math.log((N - n + 0.5) / (n + 0.5) + 1)

    # Sort by IDF descending for readability
    sorted_idf = sorted(idf.items(), key=lambda x: -x[1])

    # Write Lua module
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("-- AUTO-GENERATED by scripts/build-idf-table.py\n")
        f.write("-- Do not edit manually. Regenerate with: python scripts/build-idf-table.py\n")
        f.write("--\n")
        f.write(f"-- Source: {N} phrases from embedding-index.json\n")
        f.write(f"-- Unique tokens: {len(idf)}\n")
        f.write(f"-- Average document length: {avg_doc_length:.2f} tokens\n\n")
        f.write("return {\n")
        f.write(f"  total_docs = {N},\n")
        f.write(f"  avg_doc_length = {avg_doc_length:.4f},\n")
        f.write("  idf = {\n")
        for token, value in sorted_idf:
            # Escape any special chars in token for Lua string key
            safe_token = token.replace("\\", "\\\\").replace('"', '\\"')
            f.write(f'    ["{safe_token}"] = {value:.6f},\n')
        f.write("  },\n")
        f.write("}\n")

    print(f"Generated {output_path}")
    print(f"  Phrases: {N}")
    print(f"  Unique tokens: {len(idf)}")
    print(f"  Avg doc length: {avg_doc_length:.2f}")
    print(f"  Top 10 IDF tokens:")
    for token, value in sorted_idf[:10]:
        print(f"    {token}: {value:.4f}")
    print(f"  Bottom 5 IDF tokens:")
    for token, value in sorted_idf[-5:]:
        print(f"    {token}: {value:.4f}")

if __name__ == "__main__":
    main()
