-- engine/parser/embedding_matcher.lua
-- Tier 2 parser: loads the embedding index JSON as a phrase dictionary
-- and matches player input via token-overlap similarity (Jaccard index).
--
-- We can't run GTE-tiny inference in Lua, so the embedding vectors are
-- ignored at runtime here. The phrase TEXT is what we match against.
-- Real vector similarity comes later in the browser via ONNX Runtime Web.

local json = require("engine.parser.json")

-- BM25 data (IDF table, avg doc length) — generated by scripts/build-idf-table.py
local bm25_ok, bm25_data = pcall(require, "engine.parser.bm25_data")
if not bm25_ok then bm25_data = nil end

-- Synonym table for input expansion
local syn_ok, synonym_table = pcall(require, "engine.parser.synonym_table")
if not syn_ok then synonym_table = nil end

-- Word similarity matrix for soft matching (Phase 2)
local wsim_ok, word_sim = pcall(require, "engine.parser.word_similarity")
if not wsim_ok then word_sim = nil end

-- Context window for recency boosting (Phase 3)
local ctx_ok, context_window = pcall(require, "engine.parser.context")
if not ctx_ok then context_window = nil end

local matcher = {}
matcher.__index = matcher

-- Stop words stripped from both input and phrase text before comparison.
-- Includes common English filler that carries no game meaning for phrase matching.
local STOP_WORDS = {
  -- Determiners & pronouns
  ["the"] = true, ["a"] = true, ["an"] = true, ["some"] = true,
  ["my"] = true, ["its"] = true, ["this"] = true, ["that"] = true,
  ["it"] = true, ["i"] = true, ["me"] = true, ["you"] = true,
  ["we"] = true, ["they"] = true, ["them"] = true,
  -- Prepositions & conjunctions
  ["to"] = true, ["at"] = true, ["on"] = true, ["in"] = true,
  ["of"] = true, ["and"] = true, ["or"] = true, ["with"] = true,
  ["for"] = true, ["up"] = true, ["down"] = true, ["around"] = true,
  ["if"] = true, ["so"] = true, ["but"] = true, ["from"] = true,
  -- Modals & auxiliaries
  ["is"] = true, ["be"] = true, ["do"] = true, ["can"] = true,
  ["would"] = true, ["could"] = true, ["should"] = true,
  ["shall"] = true, ["might"] = true, ["will"] = true,
  -- Common filler verbs (not game verbs)
  ["please"] = true, ["want"] = true, ["need"] = true,
  ["try"] = true, ["let"] = true, ["go"] = true, ["like"] = true,
  -- Adverbs & adjectives (filler)
  ["now"] = true, ["just"] = true, ["here"] = true, ["right"] = true,
  ["really"] = true, ["very"] = true, ["quite"] = true,
  ["quickly"] = true, ["carefully"] = true, ["closely"] = true,
  ["gently"] = true, ["ahead"] = true,
  -- Other filler
  ["hey"] = true, ["maybe"] = true, ["perhaps"] = true,
  ["possible"] = true, ["great"] = true, ["kind"] = true,
  ["thing"] = true, ["think"] = true, ["see"] = true,
  ["hoping"] = true, ["yes"] = true, ["no"] = true, ["not"] = true,
}

---------------------------------------------------------------------------
-- Levenshtein edit distance for typo correction
---------------------------------------------------------------------------
local function levenshtein(a, b)
  local la, lb = #a, #b
  if la == 0 then return lb end
  if lb == 0 then return la end
  local matrix = {}
  for i = 0, la do
    matrix[i] = { [0] = i }
  end
  for j = 0, lb do
    matrix[0][j] = j
  end
  for i = 1, la do
    for j = 1, lb do
      local cost = (a:sub(i, i) == b:sub(j, j)) and 0 or 1
      matrix[i][j] = math.min(
        matrix[i - 1][j] + 1,
        matrix[i][j - 1] + 1,
        matrix[i - 1][j - 1] + cost
      )
    end
  end
  return matrix[la][lb]
end

---------------------------------------------------------------------------
-- Typo correction: fix misspelled verbs using known verb set.
-- Skip tokens that already exist in the BM25 IDF vocabulary — they are
-- known game-world words (nouns, adjectives) and must not be "corrected"
-- to verbs. E.g. "small" (IDF-known adjective) must not become "smell".
---------------------------------------------------------------------------
local function correct_typos(tokens, known_verbs)
  if not known_verbs or not next(known_verbs) then return tokens end
  local idf_table = bm25_data and bm25_data.idf or nil
  local corrected = {}
  for _, token in ipairs(tokens) do
    if known_verbs[token] then
      corrected[#corrected + 1] = token
    elseif idf_table and idf_table[token] then
      -- Token is a known game-world word (noun/adjective in the phrase index).
      -- Don't "correct" it to a verb — it's not a typo.
      corrected[#corrected + 1] = token
    else
      -- Short words (≤4 chars): require exact match only — no fuzzy correction.
      -- A 1-char edit on a 4-char word is 25% change, too aggressive (kick→lick).
      -- 5-char words: allow distance 1 only (knife→sniff is dist 2, too risky).
      if #token <= 4 then
        corrected[#corrected + 1] = token
      else
        local max_dist = #token <= 5 and 2 or 3  -- 5-char: dist<2, 6+: dist<3
        local best_verb, best_dist = nil, max_dist
        for verb in pairs(known_verbs) do
          if math.abs(#token - #verb) <= 2 then
            local dist = levenshtein(token, verb)
            if dist < best_dist then
              best_dist = dist
              best_verb = verb
            end
          end
        end
        if best_verb then
          corrected[#corrected + 1] = best_verb
        else
          corrected[#corrected + 1] = token
        end
      end
    end
  end
  return corrected
end

---------------------------------------------------------------------------
-- Tokenizer: lowercase, strip punctuation, remove stop words
---------------------------------------------------------------------------
local function tokenize(text)
  local tokens = {}
  local seen = {}
  for word in text:lower():gsub("[^%a%d%-]", " "):gmatch("%S+") do
    if not STOP_WORDS[word] and not seen[word] then
      tokens[#tokens + 1] = word
      seen[word] = true
    end
  end
  return tokens
end

local function token_set(tokens)
  local s = {}
  for _, t in ipairs(tokens) do s[t] = true end
  return s
end

---------------------------------------------------------------------------
-- Similarity: Jaccard index (|A ∩ B| / |A ∪ B|) with substring bonus
---------------------------------------------------------------------------
local function jaccard_with_bonus(input_tokens, phrase_tokens)
  local set_a = token_set(input_tokens)
  local set_b = token_set(phrase_tokens)

  local intersection = 0
  local union_set = {}

  for t in pairs(set_a) do union_set[t] = true end
  for t in pairs(set_b) do union_set[t] = true end

  -- Exact token matches
  for t in pairs(set_a) do
    if set_b[t] then
      intersection = intersection + 1
    end
  end

  -- Substring/prefix bonus: if an input token is a prefix of a phrase token
  -- (or vice versa), count a partial match
  local partial = 0
  for _, a in ipairs(input_tokens) do
    if not set_b[a] then
      for _, b in ipairs(phrase_tokens) do
        if not set_a[b] then
          if a:sub(1, 3) == b:sub(1, 3) and #a >= 3 and #b >= 3 then
            -- Shared 3+ char prefix → partial credit
            local overlap = 0
            for i = 1, math.min(#a, #b) do
              if a:sub(i, i) == b:sub(i, i) then overlap = overlap + 1
              else break end
            end
            partial = partial + (overlap / math.max(#a, #b)) * 0.5
          end
        end
      end
    end
  end

  local union_size = 0
  for _ in pairs(union_set) do union_size = union_size + 1 end

  if union_size == 0 then return 0 end
  return (intersection + partial) / union_size
end

---------------------------------------------------------------------------
-- Word similarity lookup (uses word_similarity.lua matrix)
-- Returns 1.0 for identical words, matrix value for known pairs, 0 otherwise.
---------------------------------------------------------------------------
local function get_similarity(w1, w2)
  if w1 == w2 then return 1.0 end
  if not word_sim then return 0.0 end
  if word_sim[w1] and word_sim[w1][w2] then
    return word_sim[w1][w2]
  end
  if word_sim[w2] and word_sim[w2][w1] then
    return word_sim[w2][w1]
  end
  return 0.0
end

---------------------------------------------------------------------------
-- Soft Cosine Measure (Sidorov et al. 2014)
-- Uses word similarity matrix S for cross-term weighting.
-- score = (q·S·p) / (sqrt(q·S·q) * sqrt(p·S·p))
---------------------------------------------------------------------------
local function soft_cosine_score(input_tokens, phrase_tokens)
  -- Build frequency maps (tokens are deduplicated by tokenizer, so freq=1)
  local q_freq, p_freq = {}, {}
  for _, t in ipairs(input_tokens) do q_freq[t] = (q_freq[t] or 0) + 1 end
  for _, t in ipairs(phrase_tokens) do p_freq[t] = (p_freq[t] or 0) + 1 end

  -- Numerator: sum over all (qi, pj) pairs weighted by similarity
  local numerator = 0
  for qi, qf in pairs(q_freq) do
    for pi, pf in pairs(p_freq) do
      local s = get_similarity(qi, pi)
      if s > 0 then
        numerator = numerator + qf * pf * s
      end
    end
  end

  -- Denominator: soft norms for proper normalization
  local norm_q = 0
  for qi, qf in pairs(q_freq) do
    for qj, qf2 in pairs(q_freq) do
      local s = get_similarity(qi, qj)
      if s > 0 then norm_q = norm_q + qf * qf2 * s end
    end
  end

  local norm_p = 0
  for pi, pf in pairs(p_freq) do
    for pj, pf2 in pairs(p_freq) do
      local s = get_similarity(pi, pj)
      if s > 0 then norm_p = norm_p + pf * pf2 * s end
    end
  end

  if norm_q <= 0 or norm_p <= 0 then return 0 end
  return numerator / (math.sqrt(norm_q) * math.sqrt(norm_p))
end

---------------------------------------------------------------------------
-- MaxSim scoring (ColBERT-inspired late interaction)
-- For each input token, find max similarity with any phrase token, sum them.
-- Normalized by input token count for comparability across inputs.
---------------------------------------------------------------------------
local function maxsim_score(input_tokens, phrase_tokens)
  if #input_tokens == 0 then return 0 end
  local total = 0
  for _, qt in ipairs(input_tokens) do
    local max_sim = 0
    for _, pt in ipairs(phrase_tokens) do
      local s = get_similarity(qt, pt)
      if s > max_sim then max_sim = s end
    end
    total = total + max_sim
  end
  return total / #input_tokens
end

---------------------------------------------------------------------------
-- BM25 scoring: IDF-weighted term frequency with length normalization
-- k1=1.2 (TF saturation), b=0.5 (moderate length norm for short docs)
---------------------------------------------------------------------------
local BM25_K1 = 1.2
local BM25_B  = 0.5

local function bm25_score(input_tokens, phrase_tokens)
  if not bm25_data or not bm25_data.idf then return 0 end

  local avgdl = bm25_data.avg_doc_length
  local doc_len = #phrase_tokens
  local idf_table = bm25_data.idf

  -- Build phrase token set for fast lookup
  local phrase_set = {}
  for _, t in ipairs(phrase_tokens) do phrase_set[t] = true end

  local score = 0
  for _, qt in ipairs(input_tokens) do
    if phrase_set[qt] then
      local idf = idf_table[qt] or 0
      -- Binary TF (tokens are deduplicated, so tf=1 if present)
      local tf = 1
      local tf_component = (tf * (BM25_K1 + 1)) /
        (tf + BM25_K1 * (1 - BM25_B + BM25_B * doc_len / avgdl))
      score = score + idf * tf_component
    end
  end

  return score
end

---------------------------------------------------------------------------
-- BM25F scoring: verb-weighted BM25 (Phase 3, Section 4.8)
-- Like standard BM25 on full phrase tokens, but when a matching token
-- is the phrase's verb, it gets boosted weight for disambiguation.
-- "light candle" → verb "light" scored 2x helps disambiguate from noun "light".
---------------------------------------------------------------------------
local BM25F_VERB_WEIGHT = 2.0
local BM25F_NOUN_WEIGHT = 1.0

local function bm25f_score(input_tokens, phrase)
  if not bm25_data or not bm25_data.idf then return 0 end

  local avgdl = bm25_data.avg_doc_length
  local doc_len = #phrase.tokens
  local idf_table = bm25_data.idf
  local verb = phrase.verb

  local phrase_set = {}
  for _, t in ipairs(phrase.tokens) do phrase_set[t] = true end

  local score = 0
  for _, qt in ipairs(input_tokens) do
    if phrase_set[qt] then
      local idf = idf_table[qt] or 0
      local weight = (qt == verb) and BM25F_VERB_WEIGHT or BM25F_NOUN_WEIGHT
      local tf = 1
      local tf_component = (tf * (BM25_K1 + 1)) /
        (tf + BM25_K1 * (1 - BM25_B + BM25_B * doc_len / avgdl))
      score = score + idf * tf_component * weight
    end
  end

  return score
end

---------------------------------------------------------------------------
-- Constructor
---------------------------------------------------------------------------
function matcher.new(index_path, debug)
  local self = setmetatable({}, matcher)
  self.phrases = {}
  self.loaded = false
  self.diagnostic = debug or false
  self.scoring_mode = "bm25"  -- "bm25", "jaccard", "softcosine", "maxsim", "phase3"

  local f = io.open(index_path, "r")
  if not f then
    io.stderr:write("[Parser] Warning: embedding index not found: " .. index_path .. "\n")
    return self
  end

  local content = f:read("*a")
  f:close()

  local ok, index = pcall(json.decode, content)
  if not ok then
    io.stderr:write("[Parser] Warning: failed to parse embedding index: " .. tostring(index) .. "\n")
    return self
  end

  -- Build phrase dictionary (we skip the embedding vectors -- Lua doesn't use them)
  for i, entry in ipairs(index.phrases or {}) do
    local phrase_tokens = tokenize(entry.text)
    local noun_tokens = entry.noun and tokenize(entry.noun) or {}
    self.phrases[#self.phrases + 1] = {
      id = i,
      text = entry.text,
      verb = entry.verb,
      noun = entry.noun,
      tokens = phrase_tokens,
      noun_tokens = noun_tokens,
    }
  end

  -- Build known-verbs set from the index for typo correction
  self.known_verbs = {}
  for _, entry in ipairs(self.phrases) do
    if entry.verb then
      self.known_verbs[entry.verb] = true
    end
  end

  -- Build inverted index: token → list of phrase references (Phase 3, Section 4.7)
  -- Enables fast candidate retrieval — only score phrases sharing tokens with input
  self.inverted_index = {}
  for _, phrase in ipairs(self.phrases) do
    for _, token in ipairs(phrase.tokens) do
      if not self.inverted_index[token] then
        self.inverted_index[token] = {}
      end
      self.inverted_index[token][#self.inverted_index[token] + 1] = phrase
    end
  end

  self.loaded = true
  if self.diagnostic then
    io.stderr:write("[Parser] Tier 2 loaded: " .. #self.phrases .. " phrases from index\n")
    -- Report inverted index stats
    local idx_count = 0
    for _ in pairs(self.inverted_index) do idx_count = idx_count + 1 end
    io.stderr:write("[Parser] Inverted index: " .. idx_count .. " unique tokens\n")
  end
  return self
end

---------------------------------------------------------------------------
-- Tiebreaker: prefer base-state (non-suffixed) noun variant.
-- "examine match" should match "examine a wooden match" not "examine a lit match".
---------------------------------------------------------------------------
local function prefer_base_state(cur_phrase, new_phrase)
  if not cur_phrase or not new_phrase then return false end
  local cur_noun = cur_phrase.noun or ""
  local new_noun = new_phrase.noun or ""
  local state_suffixes = {"%-lit$", "%-open$", "%-broken$", "%-closed$"}
  local cur_has_suffix = false
  local new_has_suffix = false
  for _, pat in ipairs(state_suffixes) do
    if cur_noun:find("-", 1, true) and cur_noun:match(pat) then cur_has_suffix = true end
    if new_noun:find("-", 1, true) and new_noun:match(pat) then new_has_suffix = true end
  end
  return cur_has_suffix and not new_has_suffix
end

---------------------------------------------------------------------------
-- match(input_text) -> verb, noun, score, matched_phrase
-- Returns the best-matching phrase's verb+noun with confidence score.
-- Returns nil if no phrases loaded.
--
-- Scoring modes:
--   "bm25"       — BM25 only (Phase 1 baseline)
--   "jaccard"    — Jaccard only (legacy)
--   "softcosine" — Two-stage: BM25 → soft cosine re-rank (Phase 2)
--   "maxsim"     — Two-stage: BM25 → MaxSim re-rank (Phase 2)
--   "phase3"     — Inverted index + BM25F + MaxSim re-rank + context boost
---------------------------------------------------------------------------
local HYBRID_BM25_WEIGHT = 0.70   -- D1 decision: 70% BM25, 30% re-rank
local HYBRID_RERANK_WEIGHT = 0.30
local RERANK_TOP_K = 50           -- Re-rank top 50 BM25 candidates
local CONTEXT_BOOST_FACTOR = 0.1  -- 10% boost per recency rank (Phase 3, 4.6)

---------------------------------------------------------------------------
-- Inverted index candidate retrieval (Phase 3, Section 4.7)
-- Returns only phrases sharing at least one token with input.
---------------------------------------------------------------------------
local function get_candidates_inverted(inverted_index, input_tokens)
  local seen = {}
  local candidates = {}
  for _, qt in ipairs(input_tokens) do
    local postings = inverted_index[qt]
    if postings then
      for _, phrase in ipairs(postings) do
        if not seen[phrase.id] then
          seen[phrase.id] = true
          candidates[#candidates + 1] = phrase
        end
      end
    end
  end
  return candidates
end

function matcher:match(input_text)
  if not self.loaded or #self.phrases == 0 then
    return nil, nil, 0, nil
  end

  local input_tokens = tokenize(input_text)
  if #input_tokens == 0 then
    return nil, nil, 0, nil
  end

  -- Synonym expansion: map unknown verbs to canonical forms
  -- before typo correction can misfire (e.g., "snatch" → "search")
  local syn_mappings = nil
  local mode = self.scoring_mode
  if mode ~= "jaccard" and synonym_table then
    input_tokens, syn_mappings = synonym_table.expand_tokens(input_tokens)
  end

  -- Apply typo correction against known verbs on remaining tokens
  input_tokens = correct_typos(input_tokens, self.known_verbs)

  -- Pure Jaccard mode (legacy) — no inverted index
  if mode == "jaccard" then
    local best_score = -1
    local best_phrase = nil
    for _, phrase in ipairs(self.phrases) do
      local score = jaccard_with_bonus(input_tokens, phrase.tokens)
      if score > best_score then
        best_score = score
        best_phrase = phrase
      elseif score == best_score and prefer_base_state(best_phrase, phrase) then
        best_phrase = phrase
      end
    end
    if best_phrase then
      return best_phrase.verb, best_phrase.noun, best_score, best_phrase.text
    end
    return nil, nil, 0, nil
  end

  -- Candidate retrieval: inverted index (phase3) vs full scan (other modes)
  local phrase_pool
  if mode == "phase3" and self.inverted_index then
    phrase_pool = get_candidates_inverted(self.inverted_index, input_tokens)
  else
    phrase_pool = self.phrases
  end

  -- Stage 1: Scoring (BM25F for phase3, standard BM25 for others)
  local use_bm25 = (bm25_data ~= nil)
  local use_bm25f = (mode == "phase3") and use_bm25
  local candidates = {}
  for _, phrase in ipairs(phrase_pool) do
    local score
    if use_bm25f then
      score = bm25f_score(input_tokens, phrase)
    elseif use_bm25 then
      score = bm25_score(input_tokens, phrase.tokens)
    else
      score = jaccard_with_bonus(input_tokens, phrase.tokens)
    end
    if score > 0 then
      candidates[#candidates + 1] = { phrase = phrase, bm25 = score, score = score }
    end
  end

  -- Pure BM25 mode — no re-ranking
  if mode == "bm25" then
    local best_score = -1
    local best_phrase = nil
    for _, c in ipairs(candidates) do
      if c.score > best_score then
        best_score = c.score
        best_phrase = c.phrase
      elseif c.score == best_score and prefer_base_state(best_phrase, c.phrase) then
        best_phrase = c.phrase
      end
    end
    if best_phrase then
      return best_phrase.verb, best_phrase.noun, best_score, best_phrase.text
    end
    return nil, nil, 0, nil
  end

  -- Stage 2: Re-rank top candidates with MaxSim or soft cosine
  table.sort(candidates, function(a, b) return a.bm25 > b.bm25 end)
  local top_k = math.min(RERANK_TOP_K, #candidates)

  -- Choose re-ranking function
  local rerank_fn
  if mode == "softcosine" then
    rerank_fn = soft_cosine_score
  else
    rerank_fn = maxsim_score  -- maxsim and phase3
  end

  -- Find max BM25 score for normalization (re-rank scores are 0-1, BM25 is unbounded)
  local max_bm25 = 0
  for i = 1, top_k do
    if candidates[i].bm25 > max_bm25 then max_bm25 = candidates[i].bm25 end
  end
  if max_bm25 <= 0 then max_bm25 = 1 end

  for i = 1, top_k do
    local rerank = rerank_fn(input_tokens, candidates[i].phrase.tokens)
    local bm25_norm = candidates[i].bm25 / max_bm25  -- Normalize BM25 to 0-1
    candidates[i].rerank = rerank
    candidates[i].score = HYBRID_BM25_WEIGHT * bm25_norm + HYBRID_RERANK_WEIGHT * rerank
  end

  -- Phase 3: Context-aware recency boost (Section 4.6)
  if mode == "phase3" and context_window then
    for i = 1, top_k do
      local noun = candidates[i].phrase.noun
      if noun then
        local recency = context_window.recency_score(noun)
        if recency > 0 then
          candidates[i].score = candidates[i].score * (1.0 + CONTEXT_BOOST_FACTOR * recency)
        end
      end
    end
  end

  -- Re-sort top-K by final score
  local top_candidates = {}
  for i = 1, top_k do top_candidates[i] = candidates[i] end
  table.sort(top_candidates, function(a, b) return a.score > b.score end)

  -- Find best with tiebreaker
  if #top_candidates > 0 then
    local best = top_candidates[1]
    -- Check tiebreakers among equal-score candidates
    for i = 2, #top_candidates do
      if top_candidates[i].score < best.score then break end
      if prefer_base_state(best.phrase, top_candidates[i].phrase) then
        best = top_candidates[i]
      end
    end
    return best.phrase.verb, best.phrase.noun, best.score, best.phrase.text
  end

  return nil, nil, 0, nil
end

return matcher
