-- engine/parser/embedding_matcher.lua
-- Tier 2 parser: loads the embedding index JSON as a phrase dictionary
-- and matches player input via BM25 scoring with Jaccard fallback.
--
-- The embedding vectors are not used at runtime — matching is purely
-- text-based using BM25 (IDF-weighted), synonym expansion, and
-- typo correction. Gracefully degrades if optional modules are missing.

local json = require("engine.parser.json")

-- BM25 data (IDF table, avg doc length) — generated by build scripts
local bm25_ok, bm25_data = pcall(require, "engine.parser.bm25_data")
if not bm25_ok then bm25_data = nil end

-- Synonym table for input expansion
local syn_ok, synonym_table = pcall(require, "engine.parser.synonym_table")
if not syn_ok then synonym_table = nil end

-- Context window for recency boost in phase3 mode
local ctx_ok, context = pcall(require, "engine.parser.context")
if not ctx_ok then context = nil end

local matcher = {}
matcher.__index = matcher

-- Stop words stripped from both input and phrase text before comparison.
-- Includes common English filler that carries no game meaning.
local STOP_WORDS = {
  -- Determiners & pronouns
  ["the"] = true, ["a"] = true, ["an"] = true, ["some"] = true,
  ["my"] = true, ["its"] = true, ["this"] = true, ["that"] = true,
  ["it"] = true, ["i"] = true, ["me"] = true, ["you"] = true,
  ["we"] = true, ["they"] = true, ["them"] = true,
  -- Prepositions & conjunctions
  ["to"] = true, ["at"] = true, ["on"] = true, ["in"] = true,
  ["of"] = true, ["and"] = true, ["or"] = true, ["with"] = true,
  ["for"] = true, ["up"] = true, ["down"] = true, ["around"] = true,
  ["if"] = true, ["so"] = true, ["but"] = true, ["from"] = true,
  -- Modals & auxiliaries
  ["is"] = true, ["be"] = true, ["do"] = true, ["can"] = true,
  ["would"] = true, ["could"] = true, ["should"] = true,
  ["shall"] = true, ["might"] = true, ["will"] = true,
  -- Common filler verbs (not game verbs)
  ["please"] = true, ["want"] = true, ["need"] = true,
  ["try"] = true, ["let"] = true, ["go"] = true, ["like"] = true,
  -- Adverbs & adjectives (filler)
  ["now"] = true, ["just"] = true, ["here"] = true, ["right"] = true,
  ["really"] = true, ["very"] = true, ["quite"] = true,
  ["quickly"] = true, ["carefully"] = true, ["closely"] = true,
  ["gently"] = true, ["ahead"] = true,
  -- Other filler
  ["hey"] = true, ["maybe"] = true, ["perhaps"] = true,
  ["possible"] = true, ["great"] = true, ["kind"] = true,
  ["thing"] = true, ["think"] = true, ["see"] = true,
  ["hoping"] = true, ["yes"] = true, ["no"] = true, ["not"] = true,
}

---------------------------------------------------------------------------
-- Levenshtein edit distance for typo correction
---------------------------------------------------------------------------
local function levenshtein(a, b)
  local la, lb = #a, #b
  if la == 0 then return lb end
  if lb == 0 then return la end
  local matrix = {}
  for i = 0, la do
    matrix[i] = { [0] = i }
  end
  for j = 0, lb do
    matrix[0][j] = j
  end
  for i = 1, la do
    for j = 1, lb do
      local cost = (a:sub(i, i) == b:sub(j, j)) and 0 or 1
      matrix[i][j] = math.min(
        matrix[i - 1][j] + 1,
        matrix[i][j - 1] + 1,
        matrix[i - 1][j - 1] + cost
      )
    end
  end
  return matrix[la][lb]
end

---------------------------------------------------------------------------
-- Typo correction: fix misspelled verbs using known verb set.
-- Skip tokens that exist in the BM25 IDF vocabulary — they are
-- known game-world words (nouns, adjectives) and must not be "corrected"
-- to verbs. E.g. "small" (IDF-known adjective) must not become "smell".
---------------------------------------------------------------------------
local function correct_typos(tokens, known_verbs)
  if not known_verbs or not next(known_verbs) then return tokens end
  local idf_table = bm25_data and bm25_data.idf or nil
  local corrected = {}
  for _, token in ipairs(tokens) do
    if known_verbs[token] then
      corrected[#corrected + 1] = token
    elseif idf_table and idf_table[token] then
      -- Token is a known game-world word — don't "correct" it to a verb
      corrected[#corrected + 1] = token
    else
      -- 4-char words: max dist 1 (conservative — kick≠lick but brek→break).
      -- 5-char words: max dist 1. 6+ chars: max dist 2.
      if #token <= 3 then
        corrected[#corrected + 1] = token
      else
        local max_dist = #token <= 5 and 1 or 2
        local best_verb, best_dist = nil, max_dist + 1
        for verb in pairs(known_verbs) do
          if math.abs(#token - #verb) <= 2 then
            local dist = levenshtein(token, verb)
            if dist < best_dist then
              best_dist = dist
              best_verb = verb
            end
          end
        end
        if best_verb then
          corrected[#corrected + 1] = best_verb
        else
          corrected[#corrected + 1] = token
        end
      end
    end
  end
  return corrected
end

---------------------------------------------------------------------------
-- Tokenizer: lowercase, strip punctuation, remove stop words
---------------------------------------------------------------------------
local function tokenize(text)
  local tokens = {}
  local seen = {}
  for word in text:lower():gsub("[^%a%d%-]", " "):gmatch("%S+") do
    if not STOP_WORDS[word] and not seen[word] then
      tokens[#tokens + 1] = word
      seen[word] = true
    end
  end
  return tokens
end

local function token_set(tokens)
  local s = {}
  for _, t in ipairs(tokens) do s[t] = true end
  return s
end

---------------------------------------------------------------------------
-- Similarity: Jaccard index (|A ∩ B| / |A ∪ B|) with substring bonus
---------------------------------------------------------------------------
local function jaccard_with_bonus(input_tokens, phrase_tokens)
  local set_a = token_set(input_tokens)
  local set_b = token_set(phrase_tokens)

  local intersection = 0
  local union_set = {}

  for t in pairs(set_a) do union_set[t] = true end
  for t in pairs(set_b) do union_set[t] = true end

  for t in pairs(set_a) do
    if set_b[t] then
      intersection = intersection + 1
    end
  end

  -- Substring/prefix bonus for near-matches
  local partial = 0
  for _, a in ipairs(input_tokens) do
    if not set_b[a] then
      for _, b in ipairs(phrase_tokens) do
        if not set_a[b] then
          if a:sub(1, 3) == b:sub(1, 3) and #a >= 3 and #b >= 3 then
            local overlap = 0
            for i = 1, math.min(#a, #b) do
              if a:sub(i, i) == b:sub(i, i) then overlap = overlap + 1
              else break end
            end
            partial = partial + (overlap / math.max(#a, #b)) * 0.5
          end
        end
      end
    end
  end

  local union_size = 0
  for _ in pairs(union_set) do union_size = union_size + 1 end

  if union_size == 0 then return 0 end
  return (intersection + partial) / union_size
end

---------------------------------------------------------------------------
-- BM25 scoring: IDF-weighted term frequency with length normalization
-- k1=1.2 (TF saturation), b=0.5 (moderate length norm for short docs)
---------------------------------------------------------------------------
local BM25_K1 = 1.2
local BM25_B  = 0.5

local function bm25_score(input_tokens, phrase_tokens)
  if not bm25_data or not bm25_data.idf then return 0 end

  local avgdl = bm25_data.avg_doc_length
  local doc_len = #phrase_tokens
  local idf_table = bm25_data.idf

  local phrase_set = {}
  for _, t in ipairs(phrase_tokens) do phrase_set[t] = true end

  local score = 0
  for _, qt in ipairs(input_tokens) do
    if phrase_set[qt] then
      local idf = idf_table[qt] or 0
      local tf = 1
      local tf_component = (tf * (BM25_K1 + 1)) /
        (tf + BM25_K1 * (1 - BM25_B + BM25_B * doc_len / avgdl))
      score = score + idf * tf_component
    end
  end

  return score
end

---------------------------------------------------------------------------
-- Tiebreaker: prefer base-state (non-suffixed) noun variant.
-- "examine match" should match "examine a wooden match" not "examine a lit match".
---------------------------------------------------------------------------
local STATE_SUFFIXES = {"%-lit$", "%-open$", "%-broken$", "%-closed$"}

local function has_state_suffix(noun)
  if not noun or not noun:find("-", 1, true) then return false end
  for _, pat in ipairs(STATE_SUFFIXES) do
    if noun:match(pat) then return true end
  end
  return false
end

local function prefer_base_state(cur_phrase, new_phrase)
  if not cur_phrase or not new_phrase then return false end
  return has_state_suffix(cur_phrase.noun) and not has_state_suffix(new_phrase.noun)
end

---------------------------------------------------------------------------
-- Constructor
---------------------------------------------------------------------------
function matcher.new(index_path, debug)
  local self = setmetatable({}, matcher)
  self.phrases = {}
  self.loaded = false
  self.diagnostic = debug or false

  local f = io.open(index_path, "r")
  if not f then
    io.stderr:write("[Parser] Warning: embedding index not found: " .. index_path .. "\n")
    return self
  end

  local content = f:read("*a")
  f:close()

  local ok, index = pcall(json.decode, content)
  if not ok then
    io.stderr:write("[Parser] Warning: failed to parse embedding index: " .. tostring(index) .. "\n")
    return self
  end

  -- Build phrase dictionary (vectors are not used — slim index only)
  for i, entry in ipairs(index.phrases or {}) do
    local noun_toks = entry.noun and tokenize(entry.noun) or {}
    self.phrases[#self.phrases + 1] = {
      id = i,
      text = entry.text,
      verb = entry.verb,
      noun = entry.noun,
      tokens = tokenize(entry.text),
      noun_tokens = noun_toks,
    }
  end

  -- Build known-verbs set from the index for typo correction
  self.known_verbs = {}
  for _, entry in ipairs(self.phrases) do
    if entry.verb then
      self.known_verbs[entry.verb] = true
    end
  end

  -- Build inverted index: token → list of phrase references
  -- Enables fast candidate retrieval for BM25 scoring
  self.inverted_index = {}
  for _, phrase in ipairs(self.phrases) do
    for _, token in ipairs(phrase.tokens) do
      if not self.inverted_index[token] then
        self.inverted_index[token] = {}
      end
      local list = self.inverted_index[token]
      list[#list + 1] = phrase
    end
  end

  self.loaded = true
  if self.diagnostic then
    io.stderr:write("[Parser] Tier 2 loaded: " .. #self.phrases .. " phrases from index\n")
    local idx_count = 0
    for _ in pairs(self.inverted_index) do idx_count = idx_count + 1 end
    io.stderr:write("[Parser] Inverted index: " .. idx_count .. " unique tokens\n")
  end
  return self
end

---------------------------------------------------------------------------
-- Inverted index candidate retrieval — only score phrases sharing tokens
---------------------------------------------------------------------------
local function get_candidates(inverted_index, input_tokens)
  local seen = {}
  local candidates = {}
  for _, qt in ipairs(input_tokens) do
    local postings = inverted_index[qt]
    if postings then
      for _, phrase in ipairs(postings) do
        if not seen[phrase.id] then
          seen[phrase.id] = true
          candidates[#candidates + 1] = phrase
        end
      end
    end
  end
  return candidates
end

---------------------------------------------------------------------------
-- match(input_text) -> verb, noun, score, matched_phrase
-- Uses BM25 scoring when IDF data is available, Jaccard as fallback.
-- Synonym expansion maps casual verbs to canonical forms before scoring.
---------------------------------------------------------------------------
function matcher:match(input_text)
  if not self.loaded or #self.phrases == 0 then
    return nil, nil, 0, nil
  end

  local input_tokens = tokenize(input_text)
  if #input_tokens == 0 then
    return nil, nil, 0, nil
  end

  -- Synonym expansion: map unknown verbs to canonical forms
  -- before typo correction can misfire (e.g., "snatch" → "search")
  if synonym_table then
    input_tokens = synonym_table.expand_tokens(input_tokens)
  end

  -- Apply typo correction against known verbs on remaining tokens
  input_tokens = correct_typos(input_tokens, self.known_verbs)

  local use_bm25 = (bm25_data ~= nil)

  -- Candidate retrieval: inverted index when BM25 is available
  local phrase_pool
  if use_bm25 and self.inverted_index then
    phrase_pool = get_candidates(self.inverted_index, input_tokens)
  else
    phrase_pool = self.phrases
  end

  -- Score all candidates
  local best_score = -1
  local best_phrase = nil
  local use_context = (self.scoring_mode == "phase3") and context and context.recency_score
  local CONTEXT_BOOST_WEIGHT = 0.1

  for _, phrase in ipairs(phrase_pool) do
    local score
    if use_bm25 then
      score = bm25_score(input_tokens, phrase.tokens)
    else
      score = jaccard_with_bonus(input_tokens, phrase.tokens)
    end

    -- Phase 3: apply context recency boost to BM25 scores
    if use_context and phrase.noun then
      local recency = context.recency_score(phrase.noun)
      if recency > 0 then
        score = score + recency * CONTEXT_BOOST_WEIGHT
      end
    end

    if score > best_score then
      best_score = score
      best_phrase = phrase
    elseif score == best_score and prefer_base_state(best_phrase, phrase) then
      best_phrase = phrase
    end
  end

  if best_phrase then
    return best_phrase.verb, best_phrase.noun, best_score, best_phrase.text
  end

  return nil, nil, 0, nil
end

return matcher
