<#
.SYNOPSIS
    Generates game-bundle.js — all Lua and JSON source files bundled for
    the Fengari web adapter.

.DESCRIPTION
    Reads every .lua and .json file under src/, JSON-encodes the contents,
    and writes a single JavaScript file that sets window.GAME_FILES and
    window.GAME_FILE_KEYS.

.EXAMPLE
    powershell web/build-bundle.ps1
#>
param(
    [string]$SrcDir,
    [string]$OutFile
)

$ErrorActionPreference = "Stop"

# Resolve paths relative to the repo root (one level up from this script)
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot  = Split-Path -Parent $ScriptDir

if (-not $SrcDir) { $SrcDir  = Join-Path $RepoRoot "src" }
if (-not $OutFile) { $OutFile = Join-Path $ScriptDir "game-bundle.js" }

Write-Host "Scanning $SrcDir for .lua and .json files..."

$files = [ordered]@{}
$count = 0

Get-ChildItem -Path $SrcDir -Recurse -File |
    Where-Object { $_.Extension -in '.lua', '.json' } |
    Sort-Object FullName |
    ForEach-Object {
        # Path relative to repo root, with forward slashes
        $relPath = $_.FullName.Substring($RepoRoot.Length + 1).Replace("\", "/")
        $content = [System.IO.File]::ReadAllText($_.FullName, [System.Text.Encoding]::UTF8)
        $files[$relPath] = $content
        $count++
    }

Write-Host "Bundling $count files..."

# Build JSON manually for maximum compatibility
# (ConvertTo-Json depth/escaping varies across PowerShell versions)
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("// game-bundle.js")
[void]$sb.AppendLine("// Auto-generated by build-bundle.ps1 -- do not edit manually.")
[void]$sb.AppendLine("// Regenerate: powershell web/build-bundle.ps1")
[void]$sb.AppendLine("//")
[void]$sb.AppendLine("// $count source files from src/")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("window.GAME_FILES = {")

$i = 0
foreach ($key in $files.Keys) {
    $i++
    $value = $files[$key]

    # JSON-escape the key (simple -- no special chars expected in paths)
    $escapedKey = $key.Replace("\", "\\").Replace('"', '\"')

    # JSON-escape the value
    $escapedValue = $value.Replace("\", "\\").Replace('"', '\"').Replace("`r`n", "\n").Replace("`n", "\n").Replace("`r", "\n").Replace("`t", "\t")

    $comma = if ($i -lt $count) { "," } else { "" }
    [void]$sb.AppendLine("  `"$escapedKey`": `"$escapedValue`"$comma")
}

[void]$sb.AppendLine("};")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("window.GAME_FILE_KEYS = Object.keys(window.GAME_FILES);")

# Write with UTF-8 encoding (no BOM for web compatibility)
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($OutFile, $sb.ToString(), $utf8NoBom)

$sizeKB = [math]::Round((Get-Item $OutFile).Length / 1024, 1)
Write-Host "Bundle written to $OutFile ($sizeKB KB, $count files)"
