<#
.SYNOPSIS
    Bundles all engine Lua files into engine.lua and compresses to engine.lua.gz.

.DESCRIPTION
    Collects all .lua files from src/engine/ and asset files from src/assets/,
    wraps each as a package.preload module, concatenates into a single engine.lua,
    then gzip-compresses to engine.lua.gz.

    Does NOT include src/meta/ files (those are served individually by build-meta.ps1).

.EXAMPLE
    powershell web/build-engine.ps1
#>
param(
    [string]$OutDir
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot  = Split-Path -Parent $ScriptDir

if (-not $OutDir) { $OutDir = Join-Path $ScriptDir "dist" }

$SrcDir    = Join-Path $RepoRoot "src"
$EngineDir = Join-Path $SrcDir "engine"
$AssetsDir = Join-Path $SrcDir "assets"

# Ensure output directory exists
if (-not (Test-Path $OutDir)) {
    New-Item -ItemType Directory -Path $OutDir -Force | Out-Null
}

Write-Host "=== build-engine.ps1 ==="

# Capture build timestamp
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm"
$timestampCompact = Get-Date -Format "yyyyMMddHHmmss"
Write-Host "Build timestamp: $timestamp ($timestampCompact)"

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("-- engine.lua")
[void]$sb.AppendLine("-- Auto-generated by build-engine.ps1 -- do not edit manually.")
[void]$sb.AppendLine("-- Contains all engine modules as package.preload entries.")
[void]$sb.AppendLine("-- Built: $timestamp")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("_G.ENGINE_BUILD_TIMESTAMP = `"$timestamp`"")
[void]$sb.AppendLine("")

$engineFileCount = 0
$assetFileCount = 0

# --- Bundle engine .lua files ---
$engineFiles = Get-ChildItem -Path $EngineDir -Recurse -File -Filter "*.lua" | Sort-Object FullName

foreach ($file in $engineFiles) {
    # Derive module name from path: src/engine/fsm/init.lua -> engine.fsm
    $relPath = $file.FullName.Substring($SrcDir.Length + 1).Replace("\", "/")
    # e.g. "engine/fsm/init.lua" or "engine/display.lua"

    $modName = $relPath -replace '\.lua$', '' -replace '/', '.'
    # "engine.fsm.init" or "engine.display"

    # Convert init modules: engine.fsm.init -> engine.fsm
    if ($modName -match '\.init$') {
        $modName = $modName -replace '\.init$', ''
    }

    $content = [System.IO.File]::ReadAllText($file.FullName, [System.Text.Encoding]::UTF8)

    [void]$sb.AppendLine("package.preload[`"$modName`"] = function()")
    [void]$sb.AppendLine($content)
    [void]$sb.AppendLine("end")
    [void]$sb.AppendLine("")

    $engineFileCount++
}

# --- Bundle asset files (embedded as VFS strings for parser) ---
# The parser needs src/assets/parser/embedding-index.json via io.open or VFS
# We embed asset files so the engine can access them via a VFS lookup

[void]$sb.AppendLine("-- Asset files (VFS)")
[void]$sb.AppendLine("if not _G.__VFS then _G.__VFS = {} end")

if (Test-Path $AssetsDir) {
    $assetFiles = Get-ChildItem -Path $AssetsDir -Recurse -File | 
        Where-Object { $_.Extension -in '.lua', '.json' } |
        Where-Object { $_.Name -ne 'embedding-index.json' -and $_.Name -ne 'embedding-index.json.gz' } |
        Sort-Object FullName

    foreach ($file in $assetFiles) {
        $relPath = $file.FullName.Substring($RepoRoot.Length + 1).Replace("\", "/")
        $content = [System.IO.File]::ReadAllText($file.FullName, [System.Text.Encoding]::UTF8)
        # Escape for Lua long string
        $content = $content.Replace("\", "\\").Replace('"', '\"')
        
        # Use a VFS table entry
        $escaped = $content -replace '\r\n', '\n' -replace '\r', '\n'
        [void]$sb.AppendLine("_G.__VFS[`"$relPath`"] = [==[")
        [void]$sb.Append([System.IO.File]::ReadAllText($file.FullName, [System.Text.Encoding]::UTF8))
        [void]$sb.AppendLine("]==]")
        [void]$sb.AppendLine("")

        $assetFileCount++
    }

    # Handle embedding-index.json specially: strip vectors
    $embeddingFile = Join-Path $AssetsDir "parser\embedding-index.json"
    if (Test-Path $embeddingFile) {
        Write-Host "  Stripping embedding vectors from embedding-index.json..."
        $jsonContent = Get-Content $embeddingFile -Raw | ConvertFrom-Json
        $stripped = @{ phrases = @() }
        foreach ($p in $jsonContent.phrases) {
            $stripped.phrases += @{
                id   = $p.id
                text = $p.text
                verb = $p.verb
                noun = $p.noun
            }
        }
        $strippedJson = $stripped | ConvertTo-Json -Depth 5 -Compress
        $relPath = "src/assets/parser/embedding-index.json"
        [void]$sb.AppendLine("_G.__VFS[`"$relPath`"] = [==[")
        [void]$sb.Append($strippedJson)
        [void]$sb.AppendLine("]==]")
        [void]$sb.AppendLine("")
        $assetFileCount++
        Write-Host "  Stripped: $([math]::Round($strippedJson.Length / 1024, 1)) KB"
    }
}

# Write raw engine.lua
$engineLuaPath = Join-Path $OutDir "engine.lua"
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($engineLuaPath, $sb.ToString(), $utf8NoBom)

$rawSize = (Get-Item $engineLuaPath).Length
$rawKB = [math]::Round($rawSize / 1024, 1)

# Gzip compress
$engineGzPath = Join-Path $OutDir "engine.lua.gz"
$rawBytes = [System.IO.File]::ReadAllBytes($engineLuaPath)
$ms = New-Object System.IO.MemoryStream
$gz = New-Object System.IO.Compression.GZipStream($ms, [System.IO.Compression.CompressionLevel]::Optimal)
$gz.Write($rawBytes, 0, $rawBytes.Length)
$gz.Close()
[System.IO.File]::WriteAllBytes($engineGzPath, $ms.ToArray())
$ms.Close()

$gzSize = (Get-Item $engineGzPath).Length
$gzKB = [math]::Round($gzSize / 1024, 1)
$ratio = [math]::Round($gzSize / $rawSize * 100, 1)

Write-Host "Bundling $engineFileCount engine files + $assetFileCount asset files..."
Write-Host "  engine.lua:    $rawKB KB (raw)"
Write-Host "  engine.lua.gz: $gzKB KB (compressed, $ratio% ratio)"

# Embed build timestamp in bootstrapper.js
$bootstrapperPath = Join-Path $ScriptDir "bootstrapper.js"
$bsContent = [System.IO.File]::ReadAllText($bootstrapperPath, $utf8NoBom)
$bsContent = $bsContent -replace 'const BUILD_TIMESTAMP = ".*?"', "const BUILD_TIMESTAMP = `"$timestamp`""
$bsContent = $bsContent -replace 'const CACHE_BUST = ".*?"', "const CACHE_BUST = `"$timestampCompact`""
[System.IO.File]::WriteAllText($bootstrapperPath, $bsContent, $utf8NoBom)
Write-Host "  Stamped bootstrapper.js: BUILD_TIMESTAMP = `"$timestamp`", CACHE_BUST = `"$timestampCompact`""

# Embed cache-bust version in index.html (bootstrapper.js?v=XXXX)
$indexPath = Join-Path $ScriptDir "index.html"
$htmlContent = [System.IO.File]::ReadAllText($indexPath, $utf8NoBom)
$htmlContent = $htmlContent -replace 'bootstrapper\.js\?v=[^"]*"', "bootstrapper.js?v=$timestampCompact`""
[System.IO.File]::WriteAllText($indexPath, $htmlContent, $utf8NoBom)
Write-Host "  Stamped index.html: bootstrapper.js?v=$timestampCompact"

Write-Host "Engine built ($timestamp) -> engine.lua.gz?t=$timestampCompact"
Write-Host "Done."
